version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --port 6379
    container_name: recruitment_redis
    hostname: recruitment_redis
    labels:
      - "name=redis"
      - "mode=standalone"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ses
    container_name: recruitment_localstack
